using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CoreRelm.Models.Migrations.Tooling.Apply
{
    public sealed record ApplyMigrationsRequest(
        // Host provides DB connection templates & server conn
        string ServerConnectionString,
        string DatabaseConnectionStringTemplate,
        // Scripts to apply (per db), typically generated by GenerateMigrations or read from disk by host
        IReadOnlyDictionary<string, IReadOnlyList<MigrationScript>> ScriptsByDatabase,
        ApplyOptions Options
    );
}
