using CoreRelm.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static CoreRelm.Enums.Indexes;

namespace CoreRelm.Attributes.BaseClasses
{
    /// <summary>
    /// Specifies index configuration metadata for a class, struct, or property to control how an index is created and
    /// managed in the underlying data store.
    /// </summary>
    /// <remarks>Apply this attribute to a class, struct, or property to define custom index settings for use
    /// by an ORM or database schema generator. Multiple instances can be applied to specify multiple indexes. Not all
    /// options may be supported by all database providers; unsupported options may be ignored.</remarks>
    /// <param name="indexName">The name of the index. If null or empty, a default name may be generated by the data provider.</param>
    /// <param name="uniquenessType">The type of uniqueness constraint to apply to the index. Determines whether the index enforces uniqueness of
    /// values.</param>
    /// <param name="indexType">The type of index to create, such as a standard or full-text index. Controls the storage and behavior of the
    /// index.</param>
    /// <param name="keyBlockSize">The key block size for the index, in bytes. Use -1 to indicate the default size. Must be a positive integer or
    /// -1.</param>
    /// <param name="parserName">The name of the parser to use for the index, if applicable. Used for specialized index types such as full-text
    /// indexes.</param>
    /// <param name="comment">A comment or description for the index. This value may be stored in the database metadata.</param>
    /// <param name="visibility">The visibility of the index, such as visible or invisible. Controls whether the index is used by the query
    /// optimizer.</param>
    /// <param name="engineAttribute">The name of the storage engine attribute to use for the index, if supported by the database engine.</param>
    /// <param name="secondaryEngineAttribute">The name of the secondary engine attribute to use for the index, if supported by the database engine.</param>
    /// <param name="algorithmType">The algorithm to use for the index, such as B-tree or hash. Determines the internal structure of the index.</param>
    /// <param name="lockOption">The lock option to use when creating or modifying the index. Controls concurrency behavior during index
    /// operations.</param>
    public class RelmIndexBase(
        string[] indexedPropertyNames = null,
        string indexName = null,
        IndexType indexType = IndexType.None,
        int keyBlockSize = -1,
        string parserName = null,
        string comment = null,
        Visibility visibility = Visibility.None,
        string engineAttribute = null,
        string secondaryEngineAttribute = null,
        Algorithm algorithmType = Algorithm.None,
        LockOption lockOption = LockOption.None
        ) : Attribute
    {
        /// <summary>
        /// Gets or sets the key value used for indexing columns during migration.
        /// </summary>
        public object? IndexKeyHolder { get; set; }

        /// <summary>
        /// Gets a value indicating whether any indexed property is sorted in descending order.
        /// </summary>
        public bool Descending => IndexedProperties?.Any(p => p.IsDescending) ?? false;

        /// <summary>
        /// Gets or sets the collection of columns that are included in the index definition.
        /// </summary>
        /// <remarks>The order and configuration of the columns in this list determine the structure of
        /// the index. Modifying this collection affects how queries utilize the index for performance
        /// optimization.</remarks>
        public List<RelmIndexColumnBase>? IndexedProperties { get; set; }



        /// <summary>
        /// Gets the names of the properties included in the index definition.
        /// </summary>
        public string[]? IndexedPropertyNames { get; set; } = indexedPropertyNames;

        /// <summary>
        /// Gets or sets the name of the index to be used for operations.
        /// </summary>
        public string? IndexName { get; set; } = indexName;

        /// <summary>
        /// Gets or sets the type of index to be created.
        /// </summary>
        public IndexType? IndexTypeValue { get; set; } = indexType;

        /// <summary>
        /// Gets or sets the name of the parser to be used for the index.
        /// </summary>
        public string? ParserName { get; set; } = parserName;

        /// <summary>
        /// Gets or sets the comment for the index.
        /// </summary>
        public string? Comment { get; set; } = comment;

        /// <summary>
        /// Gets or sets the visibility of the index.
        /// </summary>
        public Visibility? IndexVisibility { get; set; } = visibility;

        /// <summary>
        /// Gets or sets the algorithm to be used for the index.
        /// </summary>
        public Algorithm? AlgorithmType { get; set; } = algorithmType;

        /// <summary>
        /// Gets or sets the lock option for the index.
        /// </summary>
        public LockOption? IndexLockOption { get; set; } = lockOption;
    }
}
